In [1]:
import xgboost as xgb

In [2]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_digits
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
clf = xgb.XGBClassifier()

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline
df = pd.read_csv("train-2.csv")
y = df.loc[:,"Cover_Type"]
X = df.loc[:, "Elevation" : "Soil_Type40"]

In [6]:
# データの標準化
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)                   # 与えられた行列の各特徴量について､平均と標準偏差を算出
X_std = scaler.fit_transform(X) 
#scaler.fit(y)
#y_std=scaler.fit_transform(y)


In [7]:
#ライブラリをインポート
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.3, random_state=0)

In [19]:
# ハイパーパラメータ探索
clf_cv = GridSearchCV(clf, {'max_depth': [6,10,20], 'n_estimators': [200,250,300]}, verbose=1)
clf_cv.fit(X_train, y_train)
clf_cv.best_score_

Fitting 3 folds for each of 9 candidates, totalling 27 fits


[Parallel(n_jobs=1)]: Done  27 out of  27 | elapsed: 32.6min finished


0.8499622071050642

In [20]:
clf_cv.best_params_

{'max_depth': 10, 'n_estimators': 300}

In [23]:
clf = xgb.XGBClassifier(**clf_cv.best_params_)
clf.fit(X_train, y_train)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=10, min_child_weight=1, missing=None, n_estimators=300,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [25]:
pred = clf.predict(X_test)
print (confusion_matrix(y_test, pred))
print (classification_report(y_test, pred))

[[484 110   1   0   8   1  42]
 [107 454  18   0  49   8   8]
 [  0   2 559  27  14  57   0]
 [  0   0  12 619   0  11   0]
 [  2  20   8   0 584   8   0]
 [  0  10  71  10   7 573   0]
 [ 21   4   0   0   0   0 627]]
             precision    recall  f1-score   support

          1       0.79      0.75      0.77       646
          2       0.76      0.70      0.73       644
          3       0.84      0.85      0.84       659
          4       0.94      0.96      0.95       642
          5       0.88      0.94      0.91       622
          6       0.87      0.85      0.86       671
          7       0.93      0.96      0.94       652

avg / total       0.86      0.86      0.86      4536



In [ ]:
#１と２、３と６のご判断が多い
