In [1]:
import xgboost as xgb

In [2]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_digits
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
clf = xgb.XGBClassifier()

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline
df = pd.read_csv("train-2.csv")
y = df.loc[:,"Cover_Type"]
X = df.loc[:, "Elevation" : "Soil_Type40"]

In [23]:
# データの標準化
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)                   # 与えられた行列の各特徴量について､平均と標準偏差を算出
X_std = scaler.fit_transform(X) 
#scaler.fit(y)
#y_std=scaler.fit_transform(y)


In [24]:
#ライブラリをインポート
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.3, random_state=0)

In [8]:
# ハイパーパラメータ探索
clf_cv = GridSearchCV(clf, {'max_depth': [10], 'n_estimators': [550]}, verbose=1)
clf_cv.fit(X_train, y_train)
clf_cv.best_score_

Fitting 3 folds for each of 1 candidates, totalling 3 fits


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  8.5min finished


0.85090702947845809

In [9]:
clf_cv.best_params_

{'max_depth': 10, 'n_estimators': 550}

In [10]:
N=0.85100151

In [11]:
#clf = xgb.XGBClassifier(**clf_cv.best_params_)
#clf.fit(X_train, y_train)
#pred = clf.predict(X_test)
#print (confusion_matrix(y_test, pred))
#print (classification_report(y_test, pred))

In [12]:
pred = clf_cv.predict(X_test)
print (confusion_matrix(y_test, pred))
print (classification_report(y_test, pred))

[[488 105   1   0   7   1  44]
 [101 459  18   0  49   9   8]
 [  0   2 562  27  12  56   0]
 [  0   0  11 621   0  10   0]
 [  3  20   8   0 583   8   0]
 [  0  14  68  10   6 573   0]
 [ 23   4   0   0   0   0 625]]
             precision    recall  f1-score   support

          1       0.79      0.76      0.77       646
          2       0.76      0.71      0.74       644
          3       0.84      0.85      0.85       659
          4       0.94      0.97      0.96       642
          5       0.89      0.94      0.91       622
          6       0.87      0.85      0.86       671
          7       0.92      0.96      0.94       652

avg / total       0.86      0.86      0.86      4536



In [13]:
##やはり１と２、３と６が似ている（特に前者が）らしい。
##このふたつを見分ける精度を上げたい。
#データを見てみると、１と２のデータ量が少ないので、浅川博士から先週教えていただいた手法をとることにする。


In [18]:
clf_cv = GridSearchCV(clf, {'max_depth': [10], 'n_estimators': [550]}, verbose=1)
clf_cv.fit(X_, y_)
clf_cv.best_score_

Fitting 3 folds for each of 1 candidates, totalling 3 fits


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed: 13.4min finished


0.77832389721893858

In [9]:
df_ = pd.read_csv("train-2.copy.csv")#1と2の平均を取ったデータを追加した
y_ = df_.loc[:,"Cover_Type"]
X_ = df_.loc[:, "Elevation" : "Soil_Type40"]

In [26]:
pred = clf_cv.predict(X_test)
print (confusion_matrix(y_test, pred))

ValueError: feature_names mismatch: ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1', 'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4', 'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5', 'Soil_Type6', 'Soil_Type7', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10', 'Soil_Type11', 'Soil_Type12', 'Soil_Type13', 'Soil_Type14', 'Soil_Type15', 'Soil_Type16', 'Soil_Type17', 'Soil_Type18', 'Soil_Type19', 'Soil_Type20', 'Soil_Type21', 'Soil_Type22', 'Soil_Type23', 'Soil_Type24', 'Soil_Type25', 'Soil_Type26', 'Soil_Type27', 'Soil_Type28', 'Soil_Type29', 'Soil_Type30', 'Soil_Type31', 'Soil_Type32', 'Soil_Type33', 'Soil_Type34', 'Soil_Type35', 'Soil_Type36', 'Soil_Type37', 'Soil_Type38', 'Soil_Type39', 'Soil_Type40'] ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44', 'f45', 'f46', 'f47', 'f48', 'f49', 'f50', 'f51', 'f52', 'f53']
expected Soil_Type37, Soil_Type35, Soil_Type17, Soil_Type2, Soil_Type11, Soil_Type21, Soil_Type20, Wilderness_Area3, Soil_Type34, Soil_Type19, Horizontal_Distance_To_Roadways, Hillshade_Noon, Soil_Type7, Soil_Type10, Soil_Type1, Slope, Soil_Type6, Soil_Type16, Soil_Type8, Aspect, Soil_Type26, Soil_Type27, Wilderness_Area1, Hillshade_9am, Horizontal_Distance_To_Fire_Points, Soil_Type33, Elevation, Soil_Type9, Horizontal_Distance_To_Hydrology, Soil_Type24, Soil_Type3, Vertical_Distance_To_Hydrology, Soil_Type4, Soil_Type15, Soil_Type38, Wilderness_Area2, Soil_Type18, Soil_Type36, Soil_Type25, Soil_Type29, Soil_Type14, Soil_Type28, Soil_Type22, Soil_Type39, Soil_Type23, Soil_Type30, Hillshade_3pm, Soil_Type32, Wilderness_Area4, Soil_Type5, Soil_Type13, Soil_Type31, Soil_Type40, Soil_Type12 in input data
training data did not have the following fields: f18, f49, f12, f52, f20, f30, f26, f16, f1, f5, f21, f28, f32, f31, f43, f6, f44, f46, f4, f50, f37, f3, f45, f35, f39, f48, f14, f19, f22, f53, f7, f9, f36, f8, f29, f38, f13, f33, f17, f51, f15, f42, f23, f40, f10, f41, f0, f24, f2, f25, f11, f27, f34, f47

In [11]:
y_ = y_.astype("float")

In [13]:
y_[6]

1.0

In [14]:
y_=2*y_

In [15]:
y_ = y_.astype("int")

In [19]:
y_test=2*y_test

In [27]:
scaler.fit(X_)                   # 与えられた行列の各特徴量について､平均と標準偏差を算出
X__std = scaler.fit_transform(X_) 

In [29]:
X__train, X__test, y__train, y__test = train_test_split(X__std, y_, test_size=0.3, random_state=0)

In [32]:
clf_cv = GridSearchCV(clf, {'max_depth': [10], 'n_estimators': [550]}, verbose=1)
clf_cv.fit(X__train, y__train)
clf_cv.best_score_

Fitting 3 folds for each of 1 candidates, totalling 3 fits


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  9.2min finished


0.84712470002666429

In [33]:
pred = clf_cv.predict(X__test)
print (confusion_matrix(y__test, pred))
print (classification_report(y__test, pred))

[[486   3 108   0   0   8   2  28]
 [ 15 265  16   0   0   0   0   0]
 [102   1 438  18   0  48  11   6]
 [  0   0   4 514  28   7  80   0]
 [  0   0   0  10 672   0   6   0]
 [  2   0   8   5   0 609  11   0]
 [  2   0   5  62   9   5 576   0]
 [ 10   0   2   0   0   0   0 640]]
             precision    recall  f1-score   support

          2       0.79      0.77      0.78       635
          3       0.99      0.90      0.94       296
          4       0.75      0.70      0.73       624
          6       0.84      0.81      0.83       633
          8       0.95      0.98      0.96       688
         10       0.90      0.96      0.93       635
         12       0.84      0.87      0.86       659
         14       0.95      0.98      0.97       652

avg / total       0.87      0.87      0.87      4822



In [ ]:
#1と2の分類精度はそのまま、他が少しよくなった