In [2]:
import xgboost as xgb

In [3]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_digits
from sklearn.metrics import confusion_matrix, classification_report

In [4]:
clf = xgb.XGBClassifier()

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline
df = pd.read_csv("train-2.csv")
y = df.loc[:,"Cover_Type"]
X = df.loc[:, "Elevation" : "Soil_Type40"]

In [6]:
# データの標準化
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)                   # 与えられた行列の各特徴量について､平均と標準偏差を算出
X_std = scaler.fit_transform(X) 
#scaler.fit(y)
#y_std=scaler.fit_transform(y)


In [7]:
#ライブラリをインポート
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.3, random_state=0)

In [16]:
# ハイパーパラメータ探索
clf_cv = GridSearchCV(clf, {'max_depth': [10], 'n_estimators': [550]}, verbose=1)
clf_cv.fit(X_train, y_train)
clf_cv.best_score_

Fitting 3 folds for each of 1 candidates, totalling 3 fits


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:  7.8min finished


0.85090702947845809

In [13]:
clf_cv.best_params_

{'max_depth': 10, 'n_estimators': 500}

In [11]:
N=0.85100151

In [18]:
clf = xgb.XGBClassifier(**clf_cv.best_params_)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
print (confusion_matrix(y_test, pred))
print (classification_report(y_test, pred))

KeyboardInterrupt: 

In [20]:
pred = clf_cv.predict(X_test)
print (confusion_matrix(y_test, pred))
print (classification_report(y_test, pred))

[[488 105   1   0   7   1  44]
 [101 459  18   0  49   9   8]
 [  0   2 562  27  12  56   0]
 [  0   0  11 621   0  10   0]
 [  3  20   8   0 583   8   0]
 [  0  14  68  10   6 573   0]
 [ 23   4   0   0   0   0 625]]
             precision    recall  f1-score   support

          1       0.79      0.76      0.77       646
          2       0.76      0.71      0.74       644
          3       0.84      0.85      0.85       659
          4       0.94      0.97      0.96       642
          5       0.89      0.94      0.91       622
          6       0.87      0.85      0.86       671
          7       0.92      0.96      0.94       652

avg / total       0.86      0.86      0.86      4536



In [ ]:
##やはり１と２、３と６が似ている（特に前者が）らしい。
##このふたつを見分ける精度を上げたい。
#データを見てみると、１と２のデータ量が少ないので、浅川博士から先週教えていただいた手法をとることにする。
